config/routes.rb
CloudinaryCarrierwave::Application.routes.draw do

  root "products#new"
  resources "products" do
      collection do
        get 'picture_in'
        post "save_temp_pic"
        delete 'destroy_pic/:id' => 'products#destroy_pic', as: :destroy_pic
      end

  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :product
  mount_uploader :img, PictureUploader
end

app/models/picture_temp.rb
class PictureTemp < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :pictures, dependent: :destroy
	accepts_nested_attributes_for :pictures, allow_destroy: true,  :reject_if => lambda{ |a| a["img"].nil? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/products_picture.rb
module ProductsPicture
	extend ActiveSupport::Concern

	def picture_in
	    render :picture_in, layout: false
	end

	def save_temp_pic
		@temp_pic = PictureTemp.new()
		@temp_pic.public_id = params[:pic]
			respond_to do |format|
		  if @temp_pic.save!
		    format.js {render :template => "shared/save_temp_pic"}
		  end
		end
	end

	def destroy_pic
		@temp_pic = PictureTemp.find(params[:id])
		Cloudinary::Uploader.destroy(@temp_pic.public_id)
		respond_to do |format|
		  if @temp_pic.destroy
		    format.js {render :template => "shared/destroy_pic"}
		  else
		    render new
		  end
		end
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  include ProductsPicture

	def index
		@products = Product.all
		render 'show'
	end

	def show
		@products = Product.all
	end

  def new
    session[:products_params] ||= {} 
  	@product = Product.new
  	@product.pictures.build
  end

  def create
    session[:products_params].deep_merge!(without_images) if params[:product]

    submitted_hash = {}
    submitted_hash = product_params
    submitted_hash.deep_merge!(session[:products_params])

    pics = product_params[:pictures_attributes].values
    pics.each do |p|
      pid = p["img"]
      unless pid.blank?
        preloaded = Cloudinary::PreloadedFile.new(pid)
        PictureTemp.where(public_id: preloaded.public_id).first.destroy
      end
    end

    @product = Product.new(product_params)
  	@product.save!
  	redirect_to products_path

  end

  def without_images
    car_params_without_pictures = product_params
    car_params_without_pictures.delete(:pictures_attributes) if params[:product][:pictures_attributes]
    car_params_without_pictures
  end

  def product_params
  	params.required(:product).permit(:pictures_attributes => [:img, :name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_add_fields(name, f, association)
		new_obj = f.object.send(association).klass.new
		id = new_obj.object_id
		fields = f.fields_for(association,new_obj,child_index:id) do |builder|
			render("shared/#{association.to_s.singularize}_fields", f: builder)
		end
		link_to(name, "#", class: "add-fields",  data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cloudinary Carrierwave" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cloudinary Carrierwave" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="loader">
      <%= image_tag "ajax-loader2.gif" %>
    </div>
    
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/products/new.html.erb
<div id="imageStatus"></div>
<div>

	<%= form_for @product, url: {action: "create"}, :html=>{:multipart => true } do |f| %>
		<div class='pool'>
			<%= f.fields_for :pictures do |builder| %>
				<%= render 'shared/picture_fields', :f => builder %>
			<%end%>
			
		</div>
		<%= link_to_add_fields "Add More", f, :pictures %>
		<%= f.submit 'Save',class: "btn btn-primary", data: { disable_with: 'Saving...' }  %>
	<%end%>
</div>

<!-- Configure Cloudinary jQuery plugin -->
<%= cloudinary_js_config %>

app/views/products/picture_in.html.erb
<fieldset>
  <%= render 'nested_pictures', :f => f, :child_index => Time.now.to_i %>
</fields

app/views/products/show.html.erb
<h1>All Products</h1>
<% @products.each do |product|%>
	<div>
		<h1>Image</h1>
		<% product.pictures.each do |p| %>
			<div><%= p.img.full_public_id %></div>
			<div><%= cl_image_tag p.img.full_public_id, width: 60, height: 50, crop: "fit" %></div>
		<%end%>
	</div>

<%end%>

app/views/shared/_picture_fields.html.erb
<fieldset>
	<div class="row picture-uploader">
		<div class="col-md-10 upload_button_holder">
			<%= link_to("Drop here", "#", :class => "upload_button") %>
			<%= f.cl_image_upload(:img) %>
		</div>
		<div class="col-md-2">
			<%= f.hidden_field :_destroy %>
			<%= link_to "Delete", "#", :class => 'delete btn btn-danger', remote: true %>
		</div>
	</div>
</fieldset>

app/views/shared/_picture_thumb.html.erb
<%= content_tag :div, class: "image-preview", data: {public: public_id, id: id, name: name} do %>
	<%= cl_image_tag public_id, width: "50", height: "50", crop: "fit" %>
	<%= link_to('delete', destroy_pic_products_path(id),method: :delete,class: 'btn btn-danger', :remote => true, data: {confirm: 'are you sure?'}) %>
<%end%>

app/views/shared/destroy_pic.js.erb
var obj = $("div[data-public=<%= escape_javascript @temp_pic.public_id%>]");
var hidden_val = "input[name='" + obj.attr("data-name") +"']";
$(hidden_val).remove();
obj.remove();

app/views/shared/save_temp_pic.js.erb
$(".pool").prepend(
	"<%= escape_javascript render 'shared/picture_thumb', public_id: @temp_pic.public_id, id:@temp_pic.id, name: params[:name] %>"
);